/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    projects: Project;
    events: Event;
    publications: Publication;
    testimonials: Testimonial;
    team: Team;
    fellows: Fellow;
    alumni: Alumnus;
    partners: Partner;
    'form-submissions': FormSubmission;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    fellows: FellowsSelect<false> | FellowsSelect<true>;
    alumni: AlumniSelect<false> | AlumniSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'page-banners': PageBanner;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'page-banners': PageBannersSelect<false> | PageBannersSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  mfaMethod?: ('authenticator' | 'email') | null;
  emailOtpHash?: string | null;
  emailOtpExpiresAt?: string | null;
  emailOtpSentAt?: string | null;
  emailOtpAttempts?: number | null;
  /**
   * Admins manage users; editors edit content; viewers are read-only.
   */
  roles: ('admin' | 'editor' | 'viewer')[];
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos, logos, and documents. Upload here once, then pick them on any page via “Browse Media Library” on image fields. Folder only affects where new uploads are stored in R2.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Storage folder in R2. New uploads are saved under this path.
   */
  folder:
    | 'general'
    | 'blog'
    | 'fellows'
    | 'alumni'
    | 'team'
    | 'events'
    | 'projects'
    | 'pages'
    | 'publications'
    | 'partners';
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Blog articles with rich text. Set a category and tags; toggle Featured on home to show in the home page news slider.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * URL path, e.g. my-article-title
   */
  slug: string;
  /**
   * Short summary shown on listing cards and the home slider.
   */
  excerpt: string;
  featuredImage: string | Media;
  /**
   * Article body text and inline photos. Select text and use the link icon to add a hyperlink. Click + → Upload for inline images.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('blog-posts' | 'germel' | 'programme') | null;
  /**
   * Shown in the tag cloud and on the article page (e.g. Leadership, GERMEL).
   */
  tags?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  author?: string | null;
  /**
   * Show this post in the home page news/blog slider.
   */
  featuredOnHome?: boolean | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add or edit programmes. Set Detail layout to match the page design (Fellowship, P.E.A.C.E, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  /**
   * URL path, e.g. public-service-fellowship
   */
  slug: string;
  /**
   * Which detail page design this project uses.
   */
  detailLayout?: ('generic' | 'fellowship' | 'wotr' | 'peace') | null;
  category?: string | null;
  /**
   * Short description used on cards and listing pages.
   */
  summary: string;
  /**
   * Large landscape tile on the /projects page grid and the main hero on programme detail pages.
   */
  featuredImage?: (string | null) | Media;
  /**
   * Narrow portrait tile on the /projects page grid. If empty, the wide image is used instead.
   */
  visualImage?: (string | null) | Media;
  /**
   * Full Public Service Fellowship detail page, hero, tabs, programme steps, eligibility, and CTAs.
   */
  fellowshipDetail?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroDescription?: string | null;
    /**
     * Portrait image on the right. Primary uses the wide card image above.
     */
    heroSecondaryImage?: (string | null) | Media;
    badgeValue?: string | null;
    badgeLabel?: string | null;
    heroHighlights?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    heroSecondaryCtaLabel?: string | null;
    heroSecondaryCtaUrl?: string | null;
    impactEyebrow?: string | null;
    impactTitle?: string | null;
    impactStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    whyJoinEyebrow?: string | null;
    whyJoinTitle?: string | null;
    whyJoinItems?:
      | {
          title: string;
          description: string;
          /**
           * Flaticon class, e.g. flaticon-love
           */
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
    structureSidebarEyebrow?: string | null;
    structureTitle?: string | null;
    structureIntro?: string | null;
    structureSidebarImage?: (string | null) | Media;
    structureSteps?:
      | {
          title: string;
          description: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    processEyebrow?: string | null;
    processTitle?: string | null;
    processIntro?: string | null;
    processBannerImage?: (string | null) | Media;
    processSteps?:
      | {
          title: string;
          description: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    eligibilityTitle?: string | null;
    eligibilityIntro?: string | null;
    eligibilitySidebarImage?: (string | null) | Media;
    eligibilityCriteria?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    documentsTitle?: string | null;
    documents?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    inclusionNote?: string | null;
    applyEyebrow?: string | null;
    applyTitle?: string | null;
    applyDescription?: string | null;
    applyCtaLabel?: string | null;
    applyCtaUrl?: string | null;
    applySecondaryCtaLabel?: string | null;
    applySecondaryCtaUrl?: string | null;
    partnerTitle?: string | null;
    partnerCtaLabel?: string | null;
    partnerCtaUrl?: string | null;
    partnerImage?: (string | null) | Media;
  };
  /**
   * Full P.E.A.C.E detail page, hero, about, stats, outcomes, stories, gallery, and CTAs.
   */
  peaceDetail?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    heroDescription?: string | null;
    /**
     * Primary hero uses the wide card image above.
     */
    heroSecondaryImage?: (string | null) | Media;
    heroBadgeValue?: string | null;
    heroBadgeLabel?: string | null;
    heroPartners?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    aboutImage?: (string | null) | Media;
    impactTitle?: string | null;
    impactStats?:
      | {
          value: string;
          label: string;
          icon?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    outcomesTitle?: string | null;
    outcomeItems?:
      | {
          title: string;
          description: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    keySuccessEyebrow?: string | null;
    keySuccessStories?:
      | {
          title: string;
          paragraphs?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          imagePrimary?: (string | null) | Media;
          imageSecondary?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    galleryTitle?: string | null;
    galleryItems?:
      | {
          image: string | Media;
          layout: 'hero' | 'tall' | 'stack-a' | 'stack-b' | 'wide' | 'banner';
          alt: string;
          id?: string | null;
        }[]
      | null;
    relatedArticlesTitle?: string | null;
    relatedArticlesItems?:
      | {
          title: string;
          href: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    partnerTitle?: string | null;
    partnerCtaLabel?: string | null;
    partnerCtaUrl?: string | null;
    partnerImage?: (string | null) | Media;
  };
  /**
   * Full Women on the Rise detail page, hero, about, why it matters, stats, gallery, and CTAs.
   */
  wotrDetail?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    heroDescription?: string | null;
    /**
     * Primary hero uses the wide card image above.
     */
    heroSecondaryImage?: (string | null) | Media;
    heroBadgeValue?: string | null;
    heroBadgeLabel?: string | null;
    heroPartners?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    heroHighlights?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    heroSecondaryCtaLabel?: string | null;
    heroSecondaryCtaUrl?: string | null;
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    aboutImage?: (string | null) | Media;
    whyItMattersEyebrow?: string | null;
    whyItMattersTitle?: string | null;
    whyItMattersItems?:
      | {
          title: string;
          description: string;
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
    impactEyebrow?: string | null;
    impactTitle?: string | null;
    impactStats?:
      | {
          value: string;
          label: string;
          icon?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    outcomesEyebrow?: string | null;
    outcomesTitle?: string | null;
    outcomeItems?:
      | {
          title: string;
          description: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    keySuccessEyebrow?: string | null;
    keySuccessStories?:
      | {
          title: string;
          paragraphs?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          imagePrimary?: (string | null) | Media;
          imageSecondary?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    galleryEyebrow?: string | null;
    galleryTitle?: string | null;
    galleryItems?:
      | {
          image: string | Media;
          layout: 'hero' | 'tall' | 'stack-a' | 'stack-b' | 'wide' | 'banner';
          alt: string;
          id?: string | null;
        }[]
      | null;
    relatedArticlesTitle?: string | null;
    relatedArticlesItems?:
      | {
          title: string;
          href: string;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    involvedEyebrow?: string | null;
    involvedTitle?: string | null;
    involvedDescription?: string | null;
    involvedCtaLabel?: string | null;
    involvedCtaUrl?: string | null;
    involvedSecondaryCtaLabel?: string | null;
    involvedSecondaryCtaUrl?: string | null;
    partnerTitle?: string | null;
    partnerCtaLabel?: string | null;
    partnerCtaUrl?: string | null;
    partnerImage?: (string | null) | Media;
  };
  /**
   * Full project detail body (used on generic project pages).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Where this programme runs (e.g. “Nationwide” or “Greater Accra”). Not shown on the site yet, safe to leave blank.
   */
  location?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * Lower numbers show first in the Projects page bento grid.
   */
  projectsPageOrder?: number | null;
  /**
   * Show this project in the Home page Projects section.
   */
  featuredOnHome?: boolean | null;
  /**
   * Lower numbers show first in the Home Projects section.
   */
  homeOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Events with date and venue. Upcoming events appear on the home page with a countdown; past events show on News & Events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  featuredImage: string | Media;
  eventDate: string;
  venue: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Upload photos from the event. They appear on the event page as a gentle auto-sliding gallery that pauses when a visitor hovers over it. Add a few or many, the more photos, the smoother the slide.
   */
  gallery?:
    | {
        image: string | Media;
        /**
         * Optional caption shown over the photo.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full URL, including https://. Leave blank if there is nothing to register for.
   */
  registrationUrl?: string | null;
  /**
   * Text shown on the registration button. Defaults to "Register Now".
   */
  registrationLabel?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload PDFs for annual reports and research documents. Shown on /knowledge-products/annual-reports.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  description: string;
  category: 'annual-report' | 'research';
  /**
   * e.g. 2024
   */
  year?: string | null;
  /**
   * Shown on the report card (book cover style).
   */
  coverImage?: (string | null) | Media;
  /**
   * Upload the downloadable PDF. Required when status is Published.
   */
  file?: (string | null) | Media;
  /**
   * Lower numbers appear first within each section.
   */
  order?: number | null;
  status?: ('coming-soon' | 'published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fellow quotes shown on the Home page (featured) and About page (all published). Upload a portrait photo for best results.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  /**
   * e.g. Fellow, Ministry of Finance
   */
  role: string;
  /**
   * The testimonial text shown in the slider.
   */
  quote: string;
  /**
   * Portrait photo, square or portrait works best.
   */
  photo?: (string | null) | Media;
  /**
   * Show on the homepage fellow testimonials section.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  name: string;
  role: string;
  group: 'board' | 'team';
  /**
   * Lower numbers show first within the group.
   */
  order?: number | null;
  photo?: (string | null) | Media;
  bio?: string | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Current fellows shown on the Current Fellows page. Add a photo and bio so visitors can click a card to read their profile.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellows".
 */
export interface Fellow {
  id: string;
  name: string;
  institution: string;
  /**
   * Fellowship cohort label, e.g. VII
   */
  cohort?: string | null;
  /**
   * Profile photo shown on the fellow card and in the profile panel.
   */
  photo?: (string | null) | Media;
  /**
   * Profile description shown when a visitor clicks the fellow card.
   */
  bio?: string | null;
  /**
   * Optional headline for the “Fellows Highlight” section (only when Featured on page is checked).
   */
  highlightTitle?: string | null;
  /**
   * Show this fellow in the Fellows Highlight section at the top.
   */
  featuredOnPage?: boolean | null;
  /**
   * Lower numbers show first in the directory grid.
   */
  order?: number | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alumni stories and featured graduate profiles on the EPLAN page. Add photos and bios, visitors can click to read the full story.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni".
 */
export interface Alumnus {
  id: string;
  name: string;
  /**
   * e.g. Cohort II or Class of 2025
   */
  cohort?: string | null;
  /**
   * Institution or programme line shown on story cards.
   */
  institution?: string | null;
  /**
   * Role line on the Featured Graduates card (e.g. “Ministry of Health” or “Cohort Representative · Baobab Summit Delegate”).
   */
  featuredRole?: string | null;
  photo?: (string | null) | Media;
  /**
   * Story headline shown on the Alumni Stories card.
   */
  headline?: string | null;
  /**
   * Full story text, shown on the card and in the story panel.
   */
  storyBody?: string | null;
  /**
   * Shorter bio for the Featured Graduates drawer.
   */
  profileBio?: string | null;
  /**
   * Optional pull quote on the story card.
   */
  quote?: string | null;
  showInStories?: boolean | null;
  showInFeatured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Strategic partners (funders) and host institutions shown on the Our Partners page. Set status to Published to show on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  group: 'strategic' | 'host';
  /**
   * Short blurb shown on the partner card.
   */
  description?: string | null;
  /**
   * Partner logo. If empty, initials or a short name monogram is shown.
   */
  logo?: (string | null) | Media;
  /**
   * Optional abbreviation shown when there is no logo (e.g. U.S., FSD Africa).
   */
  shortName?: string | null;
  /**
   * Optional link, card becomes clickable when set.
   */
  websiteUrl?: string | null;
  /**
   * Optional tags shown on strategic partner cards (e.g. Public Service Fellowship).
   */
  programmes?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first within the group.
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages from Register Interest, Internship & Volunteering, and Partnership forms. Staff and submitters are emailed automatically on each submission.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  formType: 'register-interest' | 'internship-volunteer' | 'partnership';
  status?: ('new' | 'reviewed' | 'archived') | null;
  fullName: string;
  email: string;
  phone?: string | null;
  institution?: string | null;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Edit your existing pages. Pages are fixed. You edit their content, you don’t create or delete them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Page name (fixed).
   */
  title: string;
  /**
   * The page URL path (fixed).
   */
  slug: string;
  contact?: {
    hero?: {
      eyebrow?: string | null;
      title?: string | null;
      lead?: string | null;
      /**
       * Photo beside the contact details. Leave empty to keep the current image.
       */
      image?: (string | null) | Media;
      quickLinks?:
        | {
            label: string;
            href: string;
            id?: string | null;
          }[]
        | null;
    };
    visit?: {
      eyebrow?: string | null;
      title?: string | null;
      description?: string | null;
    };
    mapEmbedUrl?: string | null;
    formsSection?: {
      eyebrow?: string | null;
      title?: string | null;
      intro?: string | null;
    };
    forms?: {
      general?: {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        submitLabel?: string | null;
      };
      partnership?: {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        submitLabel?: string | null;
      };
    };
  };
  /**
   * Static content for the homepage. The Projects, Events and Blog sections fill in automatically from those collections, only their headings are set here.
   */
  home?: {
    heroSubtitle?: string | null;
    heroTitle?: string | null;
    heroDescription?: string | null;
    heroImage?: (string | null) | Media;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    heroStatValue?: string | null;
    heroStatLabel?: string | null;
    /**
     * The small round fellow photos beside the “Fellows trained” stat (up to 3). Falls back to default fellow photos if left empty.
     */
    heroAvatars?:
      | {
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * The rotating banner slides shown after the main one. Leave a slide image empty to keep its current photo.
     */
    heroSlides?:
      | {
          subtitle?: string | null;
          title?: string | null;
          description?: string | null;
          ctaLabel?: string | null;
          ctaHref?: string | null;
          /**
           * Main slide photo (optional, falls back to the current one).
           */
          image?: (string | null) | Media;
          /**
           * Small thumbnail for the slide selector (optional).
           */
          thumb?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    aboutSubtitle?: string | null;
    aboutTitle?: string | null;
    aboutDescription?: string | null;
    aboutImage?: (string | null) | Media;
    aboutCtaLabel?: string | null;
    aboutCtaUrl?: string | null;
    aboutMissionTitle?: string | null;
    /**
     * Checklist beside the mission title in the about section.
     */
    aboutMissionBullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Small photo beside the mission bullets on the homepage.
     */
    aboutMissionImage?: (string | null) | Media;
    missionBannerQuote?: string | null;
    /**
     * Photos that crossfade behind the mission quote. Falls back to hero slides if empty.
     */
    missionBannerImages?:
      | {
          image: string | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    coreValues?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    fellowshipTitle?: string | null;
    fellowshipDescription?: string | null;
    fellowshipCtaLabel?: string | null;
    fellowshipCtaUrl?: string | null;
    galleryHeading?: string | null;
    /**
     * Photos in the home gallery strip. Add photos to replace the current set (leave empty to keep the current photos).
     */
    gallery?:
      | {
          image: string | Media;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Headings above the auto-filled Projects, Events and Blog sections.
     */
    sections?: {
      projects?: {
        eyebrow?: string | null;
        title?: string | null;
      };
      events?: {
        eyebrow?: string | null;
        title?: string | null;
      };
      blog?: {
        eyebrow?: string | null;
        title?: string | null;
        intro?: string | null;
      };
    };
  };
  /**
   * Content for the About page (seeded from the current site content).
   */
  about?: {
    introEyebrow?: string | null;
    introLead?: string | null;
    introImage?: (string | null) | Media;
    introSecondaryImage?: (string | null) | Media;
    approachTitle?: string | null;
    approachBullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    growthHighlight?: string | null;
    growthHighlightLabel?: string | null;
    growthTitle?: string | null;
    growthBody?: string | null;
    investmentTitle?: string | null;
    investmentBody?: string | null;
    mission?: {
      eyebrow?: string | null;
      title?: string | null;
      body?: string | null;
      image?: (string | null) | Media;
    };
    vision?: {
      eyebrow?: string | null;
      title?: string | null;
      body?: string | null;
      image?: (string | null) | Media;
    };
    impact?: {
      image?: (string | null) | Media;
      heading?: string | null;
      intro?: string | null;
      items?:
        | {
            title: string;
            body: string;
            id?: string | null;
          }[]
        | null;
    };
    partner?: {
      eyebrow?: string | null;
      title?: string | null;
      lead?: string | null;
      body?: string | null;
      chooseLabel?: string | null;
      items?:
        | {
            title: string;
            body: string;
            icon?: (string | null) | Media;
            accent?: ('primary' | 'secondary' | 'deep' | 'bright') | null;
            id?: string | null;
          }[]
        | null;
    };
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Intro, approach, and CTA copy. Programme cards are managed in the Projects collection.
   */
  whatWeDo?: {
    introEyebrow?: string | null;
    introTitle?: string | null;
    introLead?: string | null;
    introParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Leave empty to keep the current image.
     */
    introImage?: (string | null) | Media;
    programmesEyebrow?: string | null;
    programmesTitle?: string | null;
    programmesCtaLabel?: string | null;
    programmesCtaUrl?: string | null;
    approachEyebrow?: string | null;
    approachTitle?: string | null;
    approachSteps?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    ctaTitle?: string | null;
    ctaBody?: string | null;
    /**
     * Leave empty to keep the current image.
     */
    ctaImage?: (string | null) | Media;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryUrl?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryUrl?: string | null;
  };
  /**
   * Portrait card (left) and message copy (right). Leave name/photo blank to use the Country Director from the Team collection.
   */
  directorMessage?: {
    /**
     * Photo shown in the card on the left. Leave empty to use the Country Director’s photo from Team.
     */
    photo?: (string | null) | Media;
    name?: string | null;
    role?: string | null;
    /**
     * Optional. Falls back to Team when empty.
     */
    email?: string | null;
    /**
     * Optional LinkedIn URL. Falls back to Team when empty.
     */
    linkedin?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    greeting?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pullQuote?: string | null;
    signoff?: string | null;
    teamCtaLabel?: string | null;
    teamCtaUrl?: string | null;
  };
  /**
   * Intro and partner CTA. The programme photo grid is built from Admin → Projects (wide/tall card images, order).
   */
  projects?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    additionalParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaTitle?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Page copy and images. Alumni stories and featured graduates are managed in the Alumni collection; community photos below.
   */
  eplanPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    heroLead?: string | null;
    heroImage?: (string | null) | Media;
    heroSecondaryImage?: (string | null) | Media;
    heroBadgeValue?: string | null;
    heroBadgeLabel?: string | null;
    heroHighlights?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    heroPrimaryCtaLabel?: string | null;
    heroPrimaryCtaUrl?: string | null;
    heroSecondaryCtaLabel?: string | null;
    heroSecondaryCtaUrl?: string | null;
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    aboutParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    aboutImage?: (string | null) | Media;
    visionEyebrow?: string | null;
    visionTitle?: string | null;
    visionText?: string | null;
    impactEyebrow?: string | null;
    impactTitle?: string | null;
    impactStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    conveningEyebrow?: string | null;
    conveningTitle?: string | null;
    conveningBody?: string | null;
    conveningImage?: (string | null) | Media;
    globalEyebrow?: string | null;
    globalTitle?: string | null;
    globalLead?: string | null;
    globalBody?: string | null;
    globalHighlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    globalImages?:
      | {
          image: string | Media;
          alt: string;
          caption?: string | null;
          layout?: ('featured' | 'poster' | 'standard') | null;
          id?: string | null;
        }[]
      | null;
    journeyEyebrow?: string | null;
    journeyTitle?: string | null;
    journeyIntro?: string | null;
    journeySteps?:
      | {
          step: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Story cards come from the Alumni collection (Show in Alumni Stories).
     */
    storiesEyebrow?: string | null;
    storiesTitle?: string | null;
    storiesIntro?: string | null;
    /**
     * Profile cards come from the Alumni collection (Show in Featured Graduates).
     */
    featuredEyebrow?: string | null;
    featuredTitle?: string | null;
    featuredIntro?: string | null;
    pathwaysEyebrow?: string | null;
    pathwaysTitle?: string | null;
    pathwaysIntro?: string | null;
    pathwaysItems?:
      | {
          title: string;
          description: string;
          icon: string;
          id?: string | null;
        }[]
      | null;
    milestoneEyebrow?: string | null;
    milestoneTitle?: string | null;
    milestoneBody?: string | null;
    milestoneCtaLabel?: string | null;
    milestoneCtaUrl?: string | null;
    milestoneImage?: (string | null) | Media;
    galleryEyebrow?: string | null;
    galleryTitle?: string | null;
    /**
     * Displayed as a scrolling photo gallery on the page.
     */
    galleryImages?:
      | {
          image: string | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
    newsEyebrow?: string | null;
    newsTitle?: string | null;
    newsIntro?: string | null;
    newsItems?:
      | {
          title: string;
          excerpt: string;
          image?: (string | null) | Media;
          href: string;
          id?: string | null;
        }[]
      | null;
    networkEyebrow?: string | null;
    networkTitle?: string | null;
    networkIntro?: string | null;
    networkBenefits?:
      | {
          title: string;
          description: string;
          icon: string;
          id?: string | null;
        }[]
      | null;
    networkGlobalLinkLabel?: string | null;
    networkGlobalLinkUrl?: string | null;
    quoteText?: string | null;
    quoteAttribution?: string | null;
    quoteRole?: string | null;
    ctaTitle?: string | null;
    ctaBody?: string | null;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryUrl?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryUrl?: string | null;
    ctaImage?: (string | null) | Media;
  };
  /**
   * Hero, engagement pathways, and fellowship register-interest form labels. Submissions appear in Form Submissions in the dashboard.
   */
  getInvolvedPage?: {
    heroEyebrow?: string | null;
    heroBadge?: string | null;
    fellowshipTitle?: string | null;
    fellowshipDescription?: string | null;
    fellowshipCtaLabel?: string | null;
    heroImage?: (string | null) | Media;
    heroSecondaryImage?: (string | null) | Media;
    imageBadgeValue?: string | null;
    imageBadgeLabel?: string | null;
    heroHighlights?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaUrl?: string | null;
    pathwaysEyebrow?: string | null;
    pathwaysTitle?: string | null;
    pathways?:
      | {
          /**
           * HTML id for in-page links (e.g. fellowship).
           */
          anchorId: string;
          title: string;
          body: string;
          bullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          ctaLabel: string;
          ctaHref: string;
          id?: string | null;
        }[]
      | null;
    registerEyebrow?: string | null;
    registerTitle?: string | null;
    registerDescription?: string | null;
    registerSubmitLabel?: string | null;
    registerPoints?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Hero, section headings, cohort band, and CTA. Fellow photos and profiles are managed in the Fellows collection.
   */
  currentFellowsPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    heroImage?: (string | null) | Media;
    heroSecondaryImage?: (string | null) | Media;
    /**
     * Section headings only, featured fellow cards come from the Fellows collection (Featured on page).
     */
    highlightsEyebrow?: string | null;
    highlightsTitle?: string | null;
    cohortLabel?: string | null;
    /**
     * Optional override for the fellow count in the heading. Leave empty to use the number of published fellows.
     */
    cohortCount?: number | null;
    cohortDescription?: string | null;
    ctaTitle?: string | null;
    ctaBody?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    ctaImage?: (string | null) | Media;
  };
  /**
   * Intro, section headings, stats, and CTA. Partner logos and descriptions are managed in the Partners collection.
   */
  partnersPage?: {
    heroEyebrow?: string | null;
    heroLead?: string | null;
    heroImage?: (string | null) | Media;
    heroSecondaryImage?: (string | null) | Media;
    heroStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    strategicEyebrow?: string | null;
    strategicTitle?: string | null;
    strategicIntro?: string | null;
    hostEyebrow?: string | null;
    hostTitle?: string | null;
    hostIntro?: string | null;
    ctaTitle?: string | null;
    ctaDescription?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Intro, section headings, and CTA. Upload reports and PDFs in the Publications collection.
   */
  annualReportsPage?: {
    heroLead?: string | null;
    introText?: string | null;
    reportsEyebrow?: string | null;
    reportsTitle?: string | null;
    relatedEyebrow?: string | null;
    relatedTitle?: string | null;
    ctaTitle?: string | null;
    ctaBody?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Heading for the Team page. Board and team members are managed in the Team collection.
   */
  team?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'fellows';
        value: string | Fellow;
      } | null)
    | ({
        relationTo: 'alumni';
        value: string | Alumnus;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  mfaMethod?: T;
  emailOtpHash?: T;
  emailOtpExpiresAt?: T;
  emailOtpSentAt?: T;
  emailOtpAttempts?: T;
  roles?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  folder?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  author?: T;
  featuredOnHome?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  detailLayout?: T;
  category?: T;
  summary?: T;
  featuredImage?: T;
  visualImage?: T;
  fellowshipDetail?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroSecondaryImage?: T;
        badgeValue?: T;
        badgeLabel?: T;
        heroHighlights?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        heroSecondaryCtaLabel?: T;
        heroSecondaryCtaUrl?: T;
        impactEyebrow?: T;
        impactTitle?: T;
        impactStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        whyJoinEyebrow?: T;
        whyJoinTitle?: T;
        whyJoinItems?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        structureSidebarEyebrow?: T;
        structureTitle?: T;
        structureIntro?: T;
        structureSidebarImage?: T;
        structureSteps?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        processEyebrow?: T;
        processTitle?: T;
        processIntro?: T;
        processBannerImage?: T;
        processSteps?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        eligibilityTitle?: T;
        eligibilityIntro?: T;
        eligibilitySidebarImage?: T;
        eligibilityCriteria?:
          | T
          | {
              text?: T;
              id?: T;
            };
        documentsTitle?: T;
        documents?:
          | T
          | {
              text?: T;
              id?: T;
            };
        inclusionNote?: T;
        applyEyebrow?: T;
        applyTitle?: T;
        applyDescription?: T;
        applyCtaLabel?: T;
        applyCtaUrl?: T;
        applySecondaryCtaLabel?: T;
        applySecondaryCtaUrl?: T;
        partnerTitle?: T;
        partnerCtaLabel?: T;
        partnerCtaUrl?: T;
        partnerImage?: T;
      };
  peaceDetail?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroDescription?: T;
        heroSecondaryImage?: T;
        heroBadgeValue?: T;
        heroBadgeLabel?: T;
        heroPartners?:
          | T
          | {
              name?: T;
              id?: T;
            };
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        aboutEyebrow?: T;
        aboutTitle?: T;
        aboutImage?: T;
        impactTitle?: T;
        impactStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
        outcomesTitle?: T;
        outcomeItems?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        keySuccessEyebrow?: T;
        keySuccessStories?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              imagePrimary?: T;
              imageSecondary?: T;
              id?: T;
            };
        galleryTitle?: T;
        galleryItems?:
          | T
          | {
              image?: T;
              layout?: T;
              alt?: T;
              id?: T;
            };
        relatedArticlesTitle?: T;
        relatedArticlesItems?:
          | T
          | {
              title?: T;
              href?: T;
              image?: T;
              id?: T;
            };
        partnerTitle?: T;
        partnerCtaLabel?: T;
        partnerCtaUrl?: T;
        partnerImage?: T;
      };
  wotrDetail?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroDescription?: T;
        heroSecondaryImage?: T;
        heroBadgeValue?: T;
        heroBadgeLabel?: T;
        heroPartners?:
          | T
          | {
              name?: T;
              id?: T;
            };
        heroHighlights?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        heroSecondaryCtaLabel?: T;
        heroSecondaryCtaUrl?: T;
        aboutEyebrow?: T;
        aboutTitle?: T;
        aboutImage?: T;
        whyItMattersEyebrow?: T;
        whyItMattersTitle?: T;
        whyItMattersItems?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        impactEyebrow?: T;
        impactTitle?: T;
        impactStats?:
          | T
          | {
              value?: T;
              label?: T;
              icon?: T;
              id?: T;
            };
        outcomesEyebrow?: T;
        outcomesTitle?: T;
        outcomeItems?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
        keySuccessEyebrow?: T;
        keySuccessStories?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              imagePrimary?: T;
              imageSecondary?: T;
              id?: T;
            };
        galleryEyebrow?: T;
        galleryTitle?: T;
        galleryItems?:
          | T
          | {
              image?: T;
              layout?: T;
              alt?: T;
              id?: T;
            };
        relatedArticlesTitle?: T;
        relatedArticlesItems?:
          | T
          | {
              title?: T;
              href?: T;
              image?: T;
              id?: T;
            };
        involvedEyebrow?: T;
        involvedTitle?: T;
        involvedDescription?: T;
        involvedCtaLabel?: T;
        involvedCtaUrl?: T;
        involvedSecondaryCtaLabel?: T;
        involvedSecondaryCtaUrl?: T;
        partnerTitle?: T;
        partnerCtaLabel?: T;
        partnerCtaUrl?: T;
        partnerImage?: T;
      };
  content?: T;
  location?: T;
  status?: T;
  projectsPageOrder?: T;
  featuredOnHome?: T;
  homeOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  eventDate?: T;
  venue?: T;
  content?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  registrationUrl?: T;
  registrationLabel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  year?: T;
  coverImage?: T;
  file?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  photo?: T;
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  group?: T;
  order?: T;
  photo?: T;
  bio?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  twitter?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellows_select".
 */
export interface FellowsSelect<T extends boolean = true> {
  name?: T;
  institution?: T;
  cohort?: T;
  photo?: T;
  bio?: T;
  highlightTitle?: T;
  featuredOnPage?: T;
  order?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  twitter?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni_select".
 */
export interface AlumniSelect<T extends boolean = true> {
  name?: T;
  cohort?: T;
  institution?: T;
  featuredRole?: T;
  photo?: T;
  headline?: T;
  storyBody?: T;
  profileBio?: T;
  quote?: T;
  showInStories?: T;
  showInFeatured?: T;
  order?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  description?: T;
  logo?: T;
  shortName?: T;
  websiteUrl?: T;
  programmes?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  status?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  institution?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contact?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              image?: T;
              quickLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
            };
        visit?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
            };
        mapEmbedUrl?: T;
        formsSection?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
            };
        forms?:
          | T
          | {
              general?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                    submitLabel?: T;
                  };
              partnership?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                    submitLabel?: T;
                  };
            };
      };
  home?:
    | T
    | {
        heroSubtitle?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroImage?: T;
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        heroStatValue?: T;
        heroStatLabel?: T;
        heroAvatars?:
          | T
          | {
              image?: T;
              id?: T;
            };
        heroSlides?:
          | T
          | {
              subtitle?: T;
              title?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              image?: T;
              thumb?: T;
              id?: T;
            };
        aboutSubtitle?: T;
        aboutTitle?: T;
        aboutDescription?: T;
        aboutImage?: T;
        aboutCtaLabel?: T;
        aboutCtaUrl?: T;
        aboutMissionTitle?: T;
        aboutMissionBullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        aboutMissionImage?: T;
        missionBannerQuote?: T;
        missionBannerImages?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        coreValues?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        fellowshipTitle?: T;
        fellowshipDescription?: T;
        fellowshipCtaLabel?: T;
        fellowshipCtaUrl?: T;
        galleryHeading?: T;
        gallery?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        sections?:
          | T
          | {
              projects?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                  };
              events?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                  };
              blog?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    intro?: T;
                  };
            };
      };
  about?:
    | T
    | {
        introEyebrow?: T;
        introLead?: T;
        introImage?: T;
        introSecondaryImage?: T;
        approachTitle?: T;
        approachBullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        growthHighlight?: T;
        growthHighlightLabel?: T;
        growthTitle?: T;
        growthBody?: T;
        investmentTitle?: T;
        investmentBody?: T;
        mission?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              image?: T;
            };
        vision?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              image?: T;
            };
        impact?:
          | T
          | {
              image?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
            };
        partner?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              body?: T;
              chooseLabel?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    icon?: T;
                    accent?: T;
                    id?: T;
                  };
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  whatWeDo?:
    | T
    | {
        introEyebrow?: T;
        introTitle?: T;
        introLead?: T;
        introParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        introImage?: T;
        programmesEyebrow?: T;
        programmesTitle?: T;
        programmesCtaLabel?: T;
        programmesCtaUrl?: T;
        approachEyebrow?: T;
        approachTitle?: T;
        approachSteps?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        ctaTitle?: T;
        ctaBody?: T;
        ctaImage?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryUrl?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryUrl?: T;
      };
  directorMessage?:
    | T
    | {
        photo?: T;
        name?: T;
        role?: T;
        email?: T;
        linkedin?: T;
        eyebrow?: T;
        title?: T;
        greeting?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pullQuote?: T;
        signoff?: T;
        teamCtaLabel?: T;
        teamCtaUrl?: T;
      };
  projects?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        additionalParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaTitle?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  eplanPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroSubtitle?: T;
        heroLead?: T;
        heroImage?: T;
        heroSecondaryImage?: T;
        heroBadgeValue?: T;
        heroBadgeLabel?: T;
        heroHighlights?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        heroPrimaryCtaLabel?: T;
        heroPrimaryCtaUrl?: T;
        heroSecondaryCtaLabel?: T;
        heroSecondaryCtaUrl?: T;
        aboutEyebrow?: T;
        aboutTitle?: T;
        aboutParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        aboutImage?: T;
        visionEyebrow?: T;
        visionTitle?: T;
        visionText?: T;
        impactEyebrow?: T;
        impactTitle?: T;
        impactStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        conveningEyebrow?: T;
        conveningTitle?: T;
        conveningBody?: T;
        conveningImage?: T;
        globalEyebrow?: T;
        globalTitle?: T;
        globalLead?: T;
        globalBody?: T;
        globalHighlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        globalImages?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
              layout?: T;
              id?: T;
            };
        journeyEyebrow?: T;
        journeyTitle?: T;
        journeyIntro?: T;
        journeySteps?:
          | T
          | {
              step?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        storiesEyebrow?: T;
        storiesTitle?: T;
        storiesIntro?: T;
        featuredEyebrow?: T;
        featuredTitle?: T;
        featuredIntro?: T;
        pathwaysEyebrow?: T;
        pathwaysTitle?: T;
        pathwaysIntro?: T;
        pathwaysItems?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        milestoneEyebrow?: T;
        milestoneTitle?: T;
        milestoneBody?: T;
        milestoneCtaLabel?: T;
        milestoneCtaUrl?: T;
        milestoneImage?: T;
        galleryEyebrow?: T;
        galleryTitle?: T;
        galleryImages?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        newsEyebrow?: T;
        newsTitle?: T;
        newsIntro?: T;
        newsItems?:
          | T
          | {
              title?: T;
              excerpt?: T;
              image?: T;
              href?: T;
              id?: T;
            };
        networkEyebrow?: T;
        networkTitle?: T;
        networkIntro?: T;
        networkBenefits?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        networkGlobalLinkLabel?: T;
        networkGlobalLinkUrl?: T;
        quoteText?: T;
        quoteAttribution?: T;
        quoteRole?: T;
        ctaTitle?: T;
        ctaBody?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryUrl?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryUrl?: T;
        ctaImage?: T;
      };
  getInvolvedPage?:
    | T
    | {
        heroEyebrow?: T;
        heroBadge?: T;
        fellowshipTitle?: T;
        fellowshipDescription?: T;
        fellowshipCtaLabel?: T;
        heroImage?: T;
        heroSecondaryImage?: T;
        imageBadgeValue?: T;
        imageBadgeLabel?: T;
        heroHighlights?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        secondaryCtaLabel?: T;
        secondaryCtaUrl?: T;
        pathwaysEyebrow?: T;
        pathwaysTitle?: T;
        pathways?:
          | T
          | {
              anchorId?: T;
              title?: T;
              body?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
        registerEyebrow?: T;
        registerTitle?: T;
        registerDescription?: T;
        registerSubmitLabel?: T;
        registerPoints?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  currentFellowsPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroImage?: T;
        heroSecondaryImage?: T;
        highlightsEyebrow?: T;
        highlightsTitle?: T;
        cohortLabel?: T;
        cohortCount?: T;
        cohortDescription?: T;
        ctaTitle?: T;
        ctaBody?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        ctaImage?: T;
      };
  partnersPage?:
    | T
    | {
        heroEyebrow?: T;
        heroLead?: T;
        heroImage?: T;
        heroSecondaryImage?: T;
        heroStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        strategicEyebrow?: T;
        strategicTitle?: T;
        strategicIntro?: T;
        hostEyebrow?: T;
        hostTitle?: T;
        hostIntro?: T;
        ctaTitle?: T;
        ctaDescription?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  annualReportsPage?:
    | T
    | {
        heroLead?: T;
        introText?: T;
        reportsEyebrow?: T;
        reportsTitle?: T;
        relatedEyebrow?: T;
        relatedTitle?: T;
        ctaTitle?: T;
        ctaBody?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  team?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  tagline?: string | null;
  /**
   * Optional. Falls back to /assets/cropped-EPL-Ghana-logo.png when empty.
   */
  logo?: (string | null) | Media;
  heroSubtitle?: string | null;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroImage?: (string | null) | Media;
  heroCtaLabel?: string | null;
  heroCtaUrl?: string | null;
  heroStatValue?: string | null;
  heroStatLabel?: string | null;
  aboutSubtitle?: string | null;
  aboutTitle?: string | null;
  aboutDescription?: string | null;
  aboutImage?: (string | null) | Media;
  aboutCtaLabel?: string | null;
  aboutCtaUrl?: string | null;
  missionBannerQuote?: string | null;
  /**
   * Optional single photo. Prefer the slideshow below for multiple images.
   */
  missionBannerImage?: (string | null) | Media;
  /**
   * Photos that crossfade behind the mission quote on the homepage. Falls back to hero slides if empty.
   */
  missionBannerImages?:
    | {
        image: string | Media;
        /**
         * Optional short label (e.g. PSF Graduation 2025)
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  fellowshipTitle?: string | null;
  fellowshipDescription?: string | null;
  fellowshipCtaLabel?: string | null;
  fellowshipCtaUrl?: string | null;
  coreValues?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Top navigation. Add a link, or leave the URL blank and add dropdown items below to turn it into a dropdown menu.
   */
  navItems?:
    | {
        label: string;
        /**
         * Where this item links to (e.g. /about). Leave blank if it only opens a dropdown.
         */
        url?: string | null;
        /**
         * Optional. Add sub-links to make this item a dropdown.
         */
        children?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Short text under the footer logo. Leave blank to use the Site Settings tagline.
   */
  aboutText?: string | null;
  /**
   * The lists of links in the footer (e.g. Quick Links, Our Programs).
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Use {year} and it will be replaced with the current year automatically.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Add a background photo to a page’s top banner. The blue overlay stays on top, so any photo still looks on-brand. Pages without a photo here stay solid blue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-banners".
 */
export interface PageBanner {
  id: string;
  /**
   * Pick a page, then upload the photo for its top banner.
   */
  banners?:
    | {
        /**
         * The page whose banner this photo is for.
         */
        page:
          | 'About Us'
          | 'What We Do'
          | 'Message from the Country Director'
          | 'Our Team'
          | 'Projects'
          | 'Our Community'
          | 'Current Fellows'
          | 'EPLAN'
          | 'Our Partners'
          | 'Knowledge Products'
          | 'Newsletter'
          | 'Get Involved'
          | 'Contact Us'
          | 'Blog'
          | 'News & Events';
        /**
         * Wide landscape photo works best (it is cropped to fill the banner).
         */
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  heroSubtitle?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  heroCtaLabel?: T;
  heroCtaUrl?: T;
  heroStatValue?: T;
  heroStatLabel?: T;
  aboutSubtitle?: T;
  aboutTitle?: T;
  aboutDescription?: T;
  aboutImage?: T;
  aboutCtaLabel?: T;
  aboutCtaUrl?: T;
  missionBannerQuote?: T;
  missionBannerImage?: T;
  missionBannerImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  fellowshipTitle?: T;
  fellowshipDescription?: T;
  fellowshipCtaLabel?: T;
  fellowshipCtaUrl?: T;
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  phone?: T;
  email?: T;
  address?: T;
  facebook?: T;
  twitter?: T;
  instagram?: T;
  youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  aboutText?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-banners_select".
 */
export interface PageBannersSelect<T extends boolean = true> {
  banners?:
    | T
    | {
        page?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}