/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    projects: Project;
    events: Event;
    publications: Publication;
    testimonials: Testimonial;
    team: Team;
    cohorts: Cohort;
    fellows: Fellow;
    'impact-interventions': ImpactIntervention;
    alumni: Alumnus;
    partners: Partner;
    'gallery-albums': GalleryAlbum;
    'form-submissions': FormSubmission;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    cohorts: {
      members: 'fellows';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    cohorts: CohortsSelect<false> | CohortsSelect<true>;
    fellows: FellowsSelect<false> | FellowsSelect<true>;
    'impact-interventions': ImpactInterventionsSelect<false> | ImpactInterventionsSelect<true>;
    alumni: AlumniSelect<false> | AlumniSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'page-banners': PageBanner;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'page-banners': PageBannersSelect<false> | PageBannersSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  mfaMethod?: ('authenticator' | 'email') | null;
  emailOtpHash?: string | null;
  emailOtpExpiresAt?: string | null;
  emailOtpSentAt?: string | null;
  emailOtpAttempts?: number | null;
  /**
   * Admins manage users; editors edit content; viewers are read-only.
   */
  roles: ('admin' | 'editor' | 'viewer')[];
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos, logos, and documents. For the Photo Gallery: create an album in Gallery Albums, then upload here and choose that album — images appear on /gallery automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Link this file to a Photo Gallery album. Uploads are stored in that album’s folder and appear on the website.
   */
  galleryAlbum?: (string | null) | GalleryAlbum;
  /**
   * Lower numbers appear first inside the album.
   */
  galleryOrder?: number | null;
  /**
   * Storage folder in R2. When a Gallery album is selected, this is set to Photo Gallery automatically.
   */
  folder:
    | 'general'
    | 'blog'
    | 'fellows'
    | 'alumni'
    | 'team'
    | 'events'
    | 'projects'
    | 'pages'
    | 'publications'
    | 'partners'
    | 'gallery';
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Create a named photo folder for the gallery. Upload images in Media → choose this album. Visitors open the album on /gallery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: string;
  title: string;
  /**
   * URL path under /gallery/, e.g. events-annual-summits
   */
  slug: string;
  category: 'events' | 'training' | 'programmes' | 'fellows-community';
  description: string;
  /**
   * Shown on the albums grid. If empty, the first linked or manual photo is used.
   */
  coverImage?: (string | null) | Media;
  /**
   * Optional extras. Most albums are managed by uploading to Media and selecting this album in the Gallery album field.
   */
  photos?:
    | {
        image: string | Media;
        title: string;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first on the gallery page.
   */
  order?: number | null;
  status?: ('published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles with rich text. Set a category and tags; toggle Featured on home to show in the home page news slider.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * URL path, e.g. my-article-title
   */
  slug: string;
  /**
   * Short summary shown on listing cards and the home slider.
   */
  excerpt: string;
  featuredImage: string | Media;
  /**
   * Article body text and inline photos. Select text and use the link icon to add a hyperlink. Click + → Upload for inline images.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('blog-posts' | 'germel' | 'programme') | null;
  /**
   * Shown in the tag cloud and on the article page (e.g. Leadership, GERMEL).
   */
  tags?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  author?: string | null;
  /**
   * Show this post in the home page news/blog slider.
   */
  featuredOnHome?: boolean | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add or edit programmes. Set Detail layout to match the page design (Fellowship, P.E.A.C.E, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * Shown in CMS lists, project cards, and the Programmes nav. For programme page H1s, also edit the matching “page content → Hero Title” below.
   */
  title: string;
  /**
   * URL path, e.g. public-service-fellowship
   */
  slug: string;
  /**
   * Which detail page design this project uses.
   */
  detailLayout?: ('generic' | 'fellowship' | 'wotr' | 'peace' | 'eplim') | null;
  category?: string | null;
  /**
   * Short description used on cards and listing pages.
   */
  summary: string;
  /**
   * Short line on the /projects cards (e.g. “500+ Fellows across 8 cohorts”).
   */
  listingMetric?: string | null;
  /**
   * Large landscape tile on the /projects page grid and the main hero on programme detail pages.
   */
  featuredImage?: (string | null) | Media;
  /**
   * Narrow portrait tile on the /projects page grid. If empty, the wide image is used instead.
   */
  visualImage?: (string | null) | Media;
  /**
   * Matches the live fellowship page: Hero, Programme Structure / Eligibility / Application Process tabs, and Apply CTA. Hero image uses the wide card image above.
   */
  fellowshipDetail?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroDescription?: string | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    structureSidebarEyebrow?: string | null;
    structureTitle?: string | null;
    structureIntro?: string | null;
    structureSteps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    eligibilityEyebrow?: string | null;
    eligibilityTitle?: string | null;
    eligibilityCriteria?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    documentsTitle?: string | null;
    documentsIntro?: string | null;
    documents?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    documentsCtaLabel?: string | null;
    processEyebrow?: string | null;
    processTitle?: string | null;
    processIntro?: string | null;
    processSteps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    applyEyebrow?: string | null;
    applyTitle?: string | null;
    applyDescription?: string | null;
    applyCtaLabel?: string | null;
    applyCtaUrl?: string | null;
  };
  /**
   * Matches the live P.E.A.C.E. page: Hero (eyebrow, title, lead, CTA; image = Featured wide card) and About + model highlight.
   */
  peaceDetail?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    /**
     * Supports **bold** with double asterisks.
     */
    heroLead?: string | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    /**
     * Body paragraphs under About. Supports **bold** with double asterisks.
     */
    aboutParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    modelHighlightEyebrow?: string | null;
    modelHighlightTitle?: string | null;
    modelHighlightBody?: string | null;
    modelHighlightAgenciesLabel?: string | null;
    modelHighlightAgencies?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Matches the live Women on the Rise page: Hero, Stats, About + pillars.
   */
  wotrDetail?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    impactStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    /**
     * Separate paragraphs with a blank line. Shown next to the about image.
     */
    heroDescription?: string | null;
    aboutImage?: (string | null) | Media;
    whyItMattersItems?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Matches the live Elevated MINDS page: hero, overview, capacity building, focus areas, and impact CTA.
   */
  eplimDetail?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    /**
     * Also used as Overview body: separate paragraphs with a blank line.
     */
    heroDescription?: string | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    aboutEyebrow?: string | null;
    aboutTitle?: string | null;
    aboutImage?: (string | null) | Media;
    capacityEyebrow?: string | null;
    capacityTitle?: string | null;
    capacityDescription?: string | null;
    capacityImage?: (string | null) | Media;
    focusEyebrow?: string | null;
    focusTitle?: string | null;
    focusItems?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    impactEyebrow?: string | null;
    impactTitle?: string | null;
    impactDescription?: string | null;
    impactImage?: (string | null) | Media;
    impactCtaLabel?: string | null;
    impactCtaUrl?: string | null;
  };
  /**
   * Full project detail body (used on generic project pages).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Where this programme runs (e.g. “Nationwide” or “Greater Accra”). Not shown on the site yet, safe to leave blank.
   */
  location?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * Lower numbers show first in the Projects page bento grid.
   */
  projectsPageOrder?: number | null;
  /**
   * Show this project in the Home page Projects section.
   */
  featuredOnHome?: boolean | null;
  /**
   * Lower numbers show first in the Home Projects section.
   */
  homeOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Events with date and venue. Upcoming events appear on the home page with a countdown; past events show on News & Events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  featuredImage: string | Media;
  eventDate: string;
  venue: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Upload photos from the event. They appear on the event page as a gentle auto-sliding gallery that pauses when a visitor hovers over it. Add a few or many, the more photos, the smoother the slide.
   */
  gallery?:
    | {
        image: string | Media;
        /**
         * Optional caption shown over the photo.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full URL, including https://. Leave blank if there is nothing to register for.
   */
  registrationUrl?: string | null;
  /**
   * Text shown on the registration button. Defaults to "Register Now".
   */
  registrationLabel?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Annual reports plus research categories (articles, factsheets, studies, policy briefs) shown on /research.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: string;
  title: string;
  /**
   * URL slug for research detail pages. Auto-derived from title if empty.
   */
  slug?: string | null;
  /**
   * Short summary shown on listing cards.
   */
  description: string;
  /**
   * Longer write-up for the detail page. Falls back to description if empty.
   */
  body?: string | null;
  category: 'annual-report' | 'articles' | 'factsheets' | 'studies' | 'technical-policy-briefs' | 'research';
  /**
   * e.g. 2024
   */
  year?: string | null;
  /**
   * Shown on research cards and detail pages.
   */
  coverImage?: (string | null) | Media;
  /**
   * Optional downloadable PDF.
   */
  file?: (string | null) | Media;
  /**
   * Lower numbers appear first within each section.
   */
  order?: number | null;
  status?: ('coming-soon' | 'published' | 'draft') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fellow quotes shown on the Home page (featured) and About page (all published). Upload a portrait photo for best results.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  /**
   * e.g. Fellow, Ministry of Finance
   */
  role: string;
  /**
   * The testimonial text shown in the slider.
   */
  quote: string;
  /**
   * Portrait photo, square or portrait works best.
   */
  photo?: (string | null) | Media;
  /**
   * Show on the homepage fellow testimonials section.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  name: string;
  role: string;
  group: 'board' | 'team';
  /**
   * Lower numbers show first within the group.
   */
  order?: number | null;
  photo?: (string | null) | Media;
  bio?: string | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create cohorts here first, then assign fellows to a cohort. Open a cohort to see its members, or use the tabs on the Fellows list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts".
 */
export interface Cohort {
  id: string;
  /**
   * Full name shown on fellow cards, e.g. Cohort 7
   */
  title: string;
  /**
   * Short label for the website tab button, e.g. C7. Falls back to title if empty.
   */
  shortLabel?: string | null;
  /**
   * Cohort number for sorting (higher = newer). Cohort 7 → 7.
   */
  number?: number | null;
  /**
   * Optional intro for this cohort on the Current Fellows page.
   */
  description?: string | null;
  /**
   * Which cohort tab opens first on /community/current-fellows. Only one should be checked.
   */
  isDefault?: boolean | null;
  /**
   * Show as a filter tab on the Current Fellows page.
   */
  showOnWebsite?: boolean | null;
  /**
   * Tab order on the website (lower numbers appear first).
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  /**
   * Everyone assigned to this cohort. To add someone, create or edit a Fellow and pick this cohort.
   */
  members?: {
    docs?: (string | Fellow)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Fellow profiles for the Current Fellows directory. Use the cohort tabs above the list to separate by cohort, or open a cohort under Cohorts to see its members.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellows".
 */
export interface Fellow {
  id: string;
  name: string;
  institution: string;
  /**
   * Which cohort this fellow belongs to. Create cohorts under Cohorts if the list is empty.
   */
  cohort: string | Cohort;
  /**
   * Profile photo shown on the fellow card and in the profile panel.
   */
  photo?: (string | null) | Media;
  /**
   * Profile description shown when a visitor clicks the fellow card.
   */
  bio?: string | null;
  /**
   * Optional headline for the “Fellows Highlight” section (only when Featured on page is checked).
   */
  highlightTitle?: string | null;
  /**
   * Show this fellow in the Fellows Highlight section at the top.
   */
  featuredOnPage?: boolean | null;
  /**
   * Show this fellow in Success Stories on /impact. Uses Impact story below, or bio if empty.
   */
  featuredOnImpact?: boolean | null;
  /**
   * Short success-story blurb for the Impact page card. Falls back to bio when empty.
   */
  impactStory?: string | null;
  /**
   * Lower numbers show first in the directory grid.
   */
  order?: number | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community intervention cards on /impact. Add a story here and publish it to show it on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-interventions".
 */
export interface ImpactIntervention {
  id: string;
  /**
   * Headline for the intervention card.
   */
  title: string;
  /**
   * URL slug for the story detail page. Derived from assembly/title if empty.
   */
  slug?: string | null;
  /**
   * e.g. Greater Accra Region
   */
  region: string;
  /**
   * Municipal assembly or locality, e.g. Kpone Katamanso
   */
  assembly: string;
  /**
   * Short summary shown on the card.
   */
  description: string;
  /**
   * Full story for the detail page. Falls back to description if empty.
   */
  body?: string | null;
  /**
   * Optional photo for the community card on /impact.
   */
  image?: (string | null) | Media;
  /**
   * Lower numbers appear first on the Impact page.
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alumni stories and featured graduate profiles on the EPLAN page. Add photos and bios, visitors can click to read the full story.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni".
 */
export interface Alumnus {
  id: string;
  name: string;
  /**
   * e.g. Cohort II or Class of 2025
   */
  cohort?: string | null;
  /**
   * Institution or programme line shown on story cards.
   */
  institution?: string | null;
  /**
   * Role line on the Featured Graduates card (e.g. “Ministry of Health” or “Cohort Representative · Baobab Summit Delegate”).
   */
  featuredRole?: string | null;
  photo?: (string | null) | Media;
  /**
   * Story headline shown on the Alumni Stories card.
   */
  headline?: string | null;
  /**
   * Full story text, shown on the card and in the story panel.
   */
  storyBody?: string | null;
  /**
   * Shorter bio for the Featured Graduates drawer.
   */
  profileBio?: string | null;
  /**
   * Optional pull quote on the story card.
   */
  quote?: string | null;
  showInStories?: boolean | null;
  showInFeatured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Strategic partners (funders) and host institutions shown on the Our Partners page. Set status to Published to show on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  group: 'strategic' | 'host';
  /**
   * Short blurb shown on the partner card.
   */
  description?: string | null;
  /**
   * Partner logo. If empty, initials or a short name monogram is shown.
   */
  logo?: (string | null) | Media;
  /**
   * Optional abbreviation shown when there is no logo (e.g. U.S., FSD Africa).
   */
  shortName?: string | null;
  /**
   * Optional link, card becomes clickable when set.
   */
  websiteUrl?: string | null;
  /**
   * Optional tags shown on strategic partner cards (e.g. Public Service Fellowship).
   */
  programmes?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first within the group.
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All website forms and Paystack payment attempts. Check “Source / page” to see where each entry came from.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  formType: 'register-interest' | 'internship-volunteer' | 'partnership' | 'pledge' | 'online-donation';
  status?: ('new' | 'reviewed' | 'archived') | null;
  /**
   * Human-readable label, e.g. “Contact page — Partnership form”.
   */
  sourcePage: string;
  /**
   * URL path, e.g. /contact or /donate.
   */
  sourcePath?: string | null;
  /**
   * For Paystack card payments only. Regular forms stay “Not a payment”.
   */
  paymentStatus?: ('none' | 'initiated' | 'completed' | 'cancelled' | 'failed') | null;
  /**
   * Set when someone starts or completes a Paystack checkout.
   */
  paymentReference?: string | null;
  fullName: string;
  email: string;
  phone?: string | null;
  institution?: string | null;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Edit your existing pages. Pages are fixed. You edit their content, you don’t create or delete them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Page name (fixed).
   */
  title: string;
  /**
   * The page URL path (fixed).
   */
  slug: string;
  contact?: {
    hero?: {
      eyebrow?: string | null;
      title?: string | null;
      lead?: string | null;
      /**
       * Photo beside the contact details. Leave empty to keep the current image.
       */
      image?: (string | null) | Media;
      quickLinks?:
        | {
            label: string;
            href: string;
            id?: string | null;
          }[]
        | null;
    };
    hub?: {
      eyebrow?: string | null;
      responseLabel?: string | null;
      responseValue?: string | null;
      hoursLabel?: string | null;
      hoursValue?: string | null;
      hqLabel?: string | null;
      hqValue?: string | null;
    };
    channels?: {
      phoneEyebrow?: string | null;
      phoneTitle?: string | null;
      phoneText?: string | null;
      phoneCtaLabel?: string | null;
      emailEyebrow?: string | null;
      emailTitle?: string | null;
      emailText?: string | null;
      emailCtaLabel?: string | null;
      visitEyebrow?: string | null;
      visitTitle?: string | null;
      visitText?: string | null;
      visitCtaLabel?: string | null;
    };
    visit?: {
      eyebrow?: string | null;
      title?: string | null;
      description?: string | null;
      addressLabel?: string | null;
      phoneLabel?: string | null;
      emailLabel?: string | null;
      note?: string | null;
    };
    mapEmbedUrl?: string | null;
    formsSection?: {
      eyebrow?: string | null;
      title?: string | null;
      intro?: string | null;
    };
    forms?: {
      general?: {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        submitLabel?: string | null;
      };
      partnership?: {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        submitLabel?: string | null;
      };
    };
  };
  /**
   * Edits the live homepage. Projects and Events cards come from those collections; set headings and copy here.
   */
  home?: {
    /**
     * Rotating hero banner. Title lines 1–3 are the three headline rows (middle line is accented).
     */
    heroSlides?:
      | {
          subtitle?: string | null;
          title?: string | null;
          titleLine1?: string | null;
          titleLine2?: string | null;
          titleLine3?: string | null;
          description?: string | null;
          ctaLabel?: string | null;
          ctaHref?: string | null;
          secondaryCtaLabel?: string | null;
          secondaryCtaHref?: string | null;
          /**
           * Full-bleed background for this slide.
           */
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    eplWayEyebrow?: string | null;
    eplWayTitle?: string | null;
    eplWayIntro?: string | null;
    eplWay?:
      | {
          number: string;
          title: string;
          description: string;
          /**
           * Longer note shown on hover.
           */
          note?: string | null;
          tone: 'blue' | 'navy' | 'gold';
          /**
           * Card photo.
           */
          image?: (string | null) | Media;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
    projectsEyebrow?: string | null;
    /**
     * Use a line break for the two-line title on the homepage.
     */
    projectsTitle?: string | null;
    statsHeading?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    impactStoriesEyebrow?: string | null;
    impactStoriesTitle?: string | null;
    impactStoriesCtaLabel?: string | null;
    impactStoriesCtaUrl?: string | null;
    impactStoriesFeaturedLabel?: string | null;
    impactStoriesFeaturedHeading?: string | null;
    impactStoriesFeaturedCtaLabel?: string | null;
    /**
     * Mark one as featured for the large card; others appear as secondary cards.
     */
    impactStories?:
      | {
          name: string;
          cohort?: string | null;
          institution?: string | null;
          quote?: string | null;
          image?: (string | null) | Media;
          /**
           * Show as the large featured story card.
           */
          featured?: boolean | null;
          /**
           * Link for the featured story CTA.
           */
          storyHref?: string | null;
          id?: string | null;
        }[]
      | null;
    eventsEyebrow?: string | null;
    eventsTitle?: string | null;
    /**
     * Small badge on the event image.
     */
    eventsBadge?: string | null;
    eventsKicker?: string | null;
    eventsRegisterLabel?: string | null;
  };
  /**
   * Edits the live About page. Team members come from the Team collection; partner logos from Partners.
   */
  about?: {
    introEyebrow?: string | null;
    introTitle?: string | null;
    introLead?: string | null;
    introImage?: (string | null) | Media;
    storyEyebrow?: string | null;
    growthTitle?: string | null;
    growthBody?: string | null;
    introSecondaryImage?: (string | null) | Media;
    mission?: {
      eyebrow?: string | null;
      title?: string | null;
      body?: string | null;
    };
    vision?: {
      eyebrow?: string | null;
      title?: string | null;
      body?: string | null;
    };
    coreValuesEyebrow?: string | null;
    coreValuesTitle?: string | null;
    coreValuesHint?: string | null;
    coreValues?:
      | {
          num?: string | null;
          title: string;
          meaning: string;
          id?: string | null;
        }[]
      | null;
    teamTitle?: string | null;
    teamIntro?: string | null;
    teamLeadershipLabel?: string | null;
    teamStaffLabel?: string | null;
    partnerEyebrow?: string | null;
    partnerTitle?: string | null;
    partnerLead?: string | null;
    partnerCtaLabel?: string | null;
    partnerCtaUrl?: string | null;
  };
  /**
   * Intro, approach, and CTA copy. Programme cards are managed in the Projects collection.
   */
  whatWeDo?: {
    introEyebrow?: string | null;
    introTitle?: string | null;
    introLead?: string | null;
    introParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Leave empty to keep the current image.
     */
    introImage?: (string | null) | Media;
    programmesEyebrow?: string | null;
    programmesTitle?: string | null;
    programmesCtaLabel?: string | null;
    programmesCtaUrl?: string | null;
    approachEyebrow?: string | null;
    approachTitle?: string | null;
    approachSteps?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    ctaTitle?: string | null;
    ctaBody?: string | null;
    /**
     * Leave empty to keep the current image.
     */
    ctaImage?: (string | null) | Media;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryUrl?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryUrl?: string | null;
  };
  /**
   * Portrait card (left) and message copy (right). Leave name/photo blank to use the Country Director from the Team collection.
   */
  directorMessage?: {
    /**
     * Photo shown in the card on the left. Leave empty to use the Country Director’s photo from Team.
     */
    photo?: (string | null) | Media;
    name?: string | null;
    role?: string | null;
    /**
     * Optional. Falls back to Team when empty.
     */
    email?: string | null;
    /**
     * Optional LinkedIn URL. Falls back to Team when empty.
     */
    linkedin?: string | null;
    eyebrow?: string | null;
    title?: string | null;
    greeting?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pullQuote?: string | null;
    signoff?: string | null;
    teamCtaLabel?: string | null;
    teamCtaUrl?: string | null;
  };
  /**
   * Intro and partner CTA. The programme photo grid is built from Admin → Projects (wide/tall card images, order).
   */
  projects?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    additionalParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaTitle?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Edits the live EPLAN page. Sections match the website: Hero, Vision, Mission, Executive Team, Beyond the Fellowship, and Network Spotlight.
   */
  eplanPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    /**
     * Full-bleed hero background. Click an image to select, then Save this page.
     */
    heroImage?: (string | null) | Media;
    /**
     * Stat row directly under the hero (value + label).
     */
    heroHighlights?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    heroPrimaryCtaLabel?: string | null;
    heroPrimaryCtaUrl?: string | null;
    heroSecondaryCtaLabel?: string | null;
    heroSecondaryCtaUrl?: string | null;
    visionEyebrow?: string | null;
    visionText?: string | null;
    missionEyebrow?: string | null;
    missionText?: string | null;
    executivesEyebrow?: string | null;
    executivesTitle?: string | null;
    executivesIntro?: string | null;
    /**
     * Roles: President, Vice President, Secretary, Communications and Public Relation Personnel, Treasurer, Organizer. Drag to reorder.
     */
    executivesItems?:
      | {
          name: string;
          role: string;
          bio?: string | null;
          photo: string | Media;
          linkedin?: string | null;
          twitter?: string | null;
          facebook?: string | null;
          instagram?: string | null;
          id?: string | null;
        }[]
      | null;
    sustainEyebrow?: string | null;
    sustainTitle?: string | null;
    sustainLead?: string | null;
    sustainNote?: string | null;
    /**
     * Image beside the Beyond the Fellowship copy.
     */
    sustainImage?: (string | null) | Media;
    sustainImageAlt?: string | null;
    sustainPillars?:
      | {
          num: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    spotlightEyebrow?: string | null;
    spotlightTitle?: string | null;
    spotlightIntro?: string | null;
    spotlightItems?:
      | {
          tag: string;
          title: string;
          description: string;
          /**
           * Link to blog/news detail, e.g. /news/my-story-slug
           */
          href?: string | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    spotlightSupportCtaLabel?: string | null;
    spotlightSupportCtaUrl?: string | null;
  };
  /**
   * Hero and section labels. Albums and photos are managed in Gallery Albums.
   */
  galleryPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    heroImage?: (string | null) | Media;
    albumsEyebrow?: string | null;
    albumsTitle?: string | null;
    albumCtaLabel?: string | null;
    photosEyebrow?: string | null;
    photosEmptyText?: string | null;
    backToGalleryLabel?: string | null;
  };
  /**
   * Landing page headline and call-to-action buttons.
   */
  getInvolvedPage?: {
    heroEyebrow?: string | null;
    fellowshipTitle?: string | null;
    fellowshipDescription?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaUrl?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaUrl?: string | null;
  };
  /**
   * Edits the live Current Fellows page. Sections match the website: Hero (with stats), Directory labels (cohort tabs from Cohorts; cards from Fellows), EPLAN promo, and Get Involved.
   */
  currentFellowsPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    /**
     * Full-bleed hero background. Click an image to select, then Save this page.
     */
    heroImage?: (string | null) | Media;
    /**
     * Four stats shown in the hero (value + label).
     */
    heroStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    searchPlaceholder?: string | null;
    sectorFilterLabel?: string | null;
    defaultRoleLabel?: string | null;
    initialVisibleCount?: number | null;
    showMoreLabel?: string | null;
    showLessLabel?: string | null;
    emptyStateText?: string | null;
    eplanEyebrow?: string | null;
    eplanTitle?: string | null;
    eplanIntro?: string | null;
    eplanStats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    eplanCtaLabel?: string | null;
    eplanCtaUrl?: string | null;
    involveEyebrow?: string | null;
    involveTitle?: string | null;
    involveBody?: string | null;
    involvePrimaryLabel?: string | null;
    involvePrimaryUrl?: string | null;
    involveSecondaryLabel?: string | null;
    involveSecondaryUrl?: string | null;
  };
  /**
   * Edits the live Partners page. Partner logos in the marquee come from the Partners collection.
   */
  partnersPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    heroCtaLabel?: string | null;
    heroCtaUrl?: string | null;
    heroImage?: (string | null) | Media;
    collabEyebrow?: string | null;
    collabTitle?: string | null;
    collabLead?: string | null;
    collabBenefits?:
      | {
          eyebrow: string;
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * e.g. 85%
     */
    collabHighlightValue?: string | null;
    /**
     * e.g. Career Advancement
     */
    collabHighlightTitle?: string | null;
    collabHighlightText?: string | null;
    collabImage?: (string | null) | Media;
    ecosystemEyebrow?: string | null;
    ecosystemTitle?: string | null;
    ecosystemIntro?: string | null;
    ecosystemLearnMoreLabel?: string | null;
    ecosystemHighlightsLabel?: string | null;
    ecosystemCategories?:
      | {
          /**
           * e.g. 01
           */
          code: string;
          title: string;
          description: string;
          highlights?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    networkTitle?: string | null;
    networkIntro?: string | null;
    formEyebrow?: string | null;
    formTitle?: string | null;
    formDescription?: string | null;
    formSubmitLabel?: string | null;
  };
  /**
   * Edits the live Donate page: Hero, Why Give, Ways to Give (card / MoMo / bank), Impact tiers, Questions, and Pledge form.
   */
  donatePage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    heroImage?: (string | null) | Media;
    heroPrimaryCtaLabel?: string | null;
    heroPrimaryCtaUrl?: string | null;
    heroSecondaryCtaLabel?: string | null;
    heroSecondaryCtaUrl?: string | null;
    whyEyebrow?: string | null;
    whyTitle?: string | null;
    whyReasons?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    waysEyebrow?: string | null;
    waysTitle?: string | null;
    waysIntro?: string | null;
    transferLabel?: string | null;
    cardStatusLabel?: string | null;
    cardCode?: string | null;
    cardTitle?: string | null;
    cardDescription?: string | null;
    cardCtaLabel?: string | null;
    cardCtaUrl?: string | null;
    momoOptions?:
      | {
          title: string;
          subtitle?: string | null;
          name: string;
          detail: string;
          detailLabel?: string | null;
          badge: string;
          /**
           * Public path, e.g. /brands/mtn-momo-mark.png
           */
          logo?: string | null;
          id?: string | null;
        }[]
      | null;
    bankTitle?: string | null;
    bankBranch?: string | null;
    bankAccountName?: string | null;
    bankAccountGhs?: string | null;
    bankAccountUsd?: string | null;
    bankName?: string | null;
    bankSwift?: string | null;
    bankSortCode?: string | null;
    bankNote?: string | null;
    tiersEyebrow?: string | null;
    tiersTitle?: string | null;
    tierItems?:
      | {
          label: string;
          amountDisplay: string;
          amountGhs: string;
          amountUsd: string;
          description: string;
          isCustom?: boolean | null;
          id?: string | null;
        }[]
      | null;
    questionsTitle?: string | null;
    questionsText?: string | null;
    questionsPrimaryLabel?: string | null;
    questionsPrimaryUrl?: string | null;
    questionsSecondaryLabel?: string | null;
    questionsSecondaryUrl?: string | null;
    pledgeEyebrow?: string | null;
    pledgeTitle?: string | null;
    pledgeDescription?: string | null;
    pledgeSubmitLabel?: string | null;
    pledgeSuccessTitle?: string | null;
    pledgeSuccessText?: string | null;
    /**
     * Preferred giving channel dropdown options (no Telecel / AT by default).
     */
    pledgeChannels?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Edits the live Impact page. Fellows, Impact Interventions, and Publications supply the cards; set section copy here.
   */
  impactPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroDescription?: string | null;
    heroImage?: (string | null) | Media;
    glanceEyebrow?: string | null;
    glanceStats?:
      | {
          value: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    successEyebrow?: string | null;
    successTitle?: string | null;
    communityEyebrow?: string | null;
    communityTitle?: string | null;
    communityIntro?: string | null;
    communityCtaLabel?: string | null;
    communityCtaUrl?: string | null;
    testimonialsEyebrow?: string | null;
    testimonialsTitle?: string | null;
    testimonialsIntro?: string | null;
    testimonials?:
      | {
          category: 'Supervisors' | 'Mentors' | 'Partnered Institutions';
          quote: string;
          author: string;
          role: string;
          org: string;
          photo?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    publicationsEyebrow?: string | null;
    publicationsTitle?: string | null;
    publicationsIntro?: string | null;
    reportsHeading?: string | null;
    reportsCtaLabel?: string | null;
    /**
     * Fallback link when a report has no PDF file.
     */
    reportsCtaUrl?: string | null;
    researchHeading?: string | null;
    researchCtaLabel?: string | null;
    /**
     * Fallback link when a study has no detail URL or file.
     */
    researchCtaUrl?: string | null;
  };
  /**
   * Intro, section headings, and CTA. Upload reports and PDFs in the Publications collection.
   */
  annualReportsPage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroLead?: string | null;
    introText?: string | null;
    heroImage?: (string | null) | Media;
    reportsEyebrow?: string | null;
    reportsTitle?: string | null;
    relatedEyebrow?: string | null;
    relatedTitle?: string | null;
    ctaTitle?: string | null;
    ctaBody?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  /**
   * Heading for the Team page. Board and team members are managed in the Team collection.
   */
  team?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'publications';
        value: string | Publication;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'cohorts';
        value: string | Cohort;
      } | null)
    | ({
        relationTo: 'fellows';
        value: string | Fellow;
      } | null)
    | ({
        relationTo: 'impact-interventions';
        value: string | ImpactIntervention;
      } | null)
    | ({
        relationTo: 'alumni';
        value: string | Alumnus;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: string | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  mfaMethod?: T;
  emailOtpHash?: T;
  emailOtpExpiresAt?: T;
  emailOtpSentAt?: T;
  emailOtpAttempts?: T;
  roles?: T;
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  galleryAlbum?: T;
  galleryOrder?: T;
  folder?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  author?: T;
  featuredOnHome?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  detailLayout?: T;
  category?: T;
  summary?: T;
  listingMetric?: T;
  featuredImage?: T;
  visualImage?: T;
  fellowshipDetail?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        structureSidebarEyebrow?: T;
        structureTitle?: T;
        structureIntro?: T;
        structureSteps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        eligibilityEyebrow?: T;
        eligibilityTitle?: T;
        eligibilityCriteria?:
          | T
          | {
              text?: T;
              id?: T;
            };
        documentsTitle?: T;
        documentsIntro?: T;
        documents?:
          | T
          | {
              text?: T;
              id?: T;
            };
        documentsCtaLabel?: T;
        processEyebrow?: T;
        processTitle?: T;
        processIntro?: T;
        processSteps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        applyEyebrow?: T;
        applyTitle?: T;
        applyDescription?: T;
        applyCtaLabel?: T;
        applyCtaUrl?: T;
      };
  peaceDetail?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        aboutEyebrow?: T;
        aboutTitle?: T;
        aboutParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        modelHighlightEyebrow?: T;
        modelHighlightTitle?: T;
        modelHighlightBody?: T;
        modelHighlightAgenciesLabel?: T;
        modelHighlightAgencies?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  wotrDetail?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        impactStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        aboutEyebrow?: T;
        aboutTitle?: T;
        heroDescription?: T;
        aboutImage?: T;
        whyItMattersItems?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  eplimDetail?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroDescription?: T;
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        aboutEyebrow?: T;
        aboutTitle?: T;
        aboutImage?: T;
        capacityEyebrow?: T;
        capacityTitle?: T;
        capacityDescription?: T;
        capacityImage?: T;
        focusEyebrow?: T;
        focusTitle?: T;
        focusItems?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        impactEyebrow?: T;
        impactTitle?: T;
        impactDescription?: T;
        impactImage?: T;
        impactCtaLabel?: T;
        impactCtaUrl?: T;
      };
  content?: T;
  location?: T;
  status?: T;
  projectsPageOrder?: T;
  featuredOnHome?: T;
  homeOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  eventDate?: T;
  venue?: T;
  content?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  registrationUrl?: T;
  registrationLabel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  body?: T;
  category?: T;
  year?: T;
  coverImage?: T;
  file?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  photo?: T;
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  group?: T;
  order?: T;
  photo?: T;
  bio?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  twitter?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts_select".
 */
export interface CohortsSelect<T extends boolean = true> {
  title?: T;
  shortLabel?: T;
  number?: T;
  description?: T;
  isDefault?: T;
  showOnWebsite?: T;
  order?: T;
  status?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellows_select".
 */
export interface FellowsSelect<T extends boolean = true> {
  name?: T;
  institution?: T;
  cohort?: T;
  photo?: T;
  bio?: T;
  highlightTitle?: T;
  featuredOnPage?: T;
  featuredOnImpact?: T;
  impactStory?: T;
  order?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  twitter?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-interventions_select".
 */
export interface ImpactInterventionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  region?: T;
  assembly?: T;
  description?: T;
  body?: T;
  image?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni_select".
 */
export interface AlumniSelect<T extends boolean = true> {
  name?: T;
  cohort?: T;
  institution?: T;
  featuredRole?: T;
  photo?: T;
  headline?: T;
  storyBody?: T;
  profileBio?: T;
  quote?: T;
  showInStories?: T;
  showInFeatured?: T;
  order?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  description?: T;
  logo?: T;
  shortName?: T;
  websiteUrl?: T;
  programmes?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  description?: T;
  coverImage?: T;
  photos?:
    | T
    | {
        image?: T;
        title?: T;
        caption?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  status?: T;
  sourcePage?: T;
  sourcePath?: T;
  paymentStatus?: T;
  paymentReference?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  institution?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contact?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lead?: T;
              image?: T;
              quickLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
            };
        hub?:
          | T
          | {
              eyebrow?: T;
              responseLabel?: T;
              responseValue?: T;
              hoursLabel?: T;
              hoursValue?: T;
              hqLabel?: T;
              hqValue?: T;
            };
        channels?:
          | T
          | {
              phoneEyebrow?: T;
              phoneTitle?: T;
              phoneText?: T;
              phoneCtaLabel?: T;
              emailEyebrow?: T;
              emailTitle?: T;
              emailText?: T;
              emailCtaLabel?: T;
              visitEyebrow?: T;
              visitTitle?: T;
              visitText?: T;
              visitCtaLabel?: T;
            };
        visit?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              addressLabel?: T;
              phoneLabel?: T;
              emailLabel?: T;
              note?: T;
            };
        mapEmbedUrl?: T;
        formsSection?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
            };
        forms?:
          | T
          | {
              general?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                    submitLabel?: T;
                  };
              partnership?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                    submitLabel?: T;
                  };
            };
      };
  home?:
    | T
    | {
        heroSlides?:
          | T
          | {
              subtitle?: T;
              title?: T;
              titleLine1?: T;
              titleLine2?: T;
              titleLine3?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              image?: T;
              id?: T;
            };
        eplWayEyebrow?: T;
        eplWayTitle?: T;
        eplWayIntro?: T;
        eplWay?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              note?: T;
              tone?: T;
              image?: T;
              href?: T;
              id?: T;
            };
        projectsEyebrow?: T;
        projectsTitle?: T;
        statsHeading?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        impactStoriesEyebrow?: T;
        impactStoriesTitle?: T;
        impactStoriesCtaLabel?: T;
        impactStoriesCtaUrl?: T;
        impactStoriesFeaturedLabel?: T;
        impactStoriesFeaturedHeading?: T;
        impactStoriesFeaturedCtaLabel?: T;
        impactStories?:
          | T
          | {
              name?: T;
              cohort?: T;
              institution?: T;
              quote?: T;
              image?: T;
              featured?: T;
              storyHref?: T;
              id?: T;
            };
        eventsEyebrow?: T;
        eventsTitle?: T;
        eventsBadge?: T;
        eventsKicker?: T;
        eventsRegisterLabel?: T;
      };
  about?:
    | T
    | {
        introEyebrow?: T;
        introTitle?: T;
        introLead?: T;
        introImage?: T;
        storyEyebrow?: T;
        growthTitle?: T;
        growthBody?: T;
        introSecondaryImage?: T;
        mission?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
            };
        vision?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
            };
        coreValuesEyebrow?: T;
        coreValuesTitle?: T;
        coreValuesHint?: T;
        coreValues?:
          | T
          | {
              num?: T;
              title?: T;
              meaning?: T;
              id?: T;
            };
        teamTitle?: T;
        teamIntro?: T;
        teamLeadershipLabel?: T;
        teamStaffLabel?: T;
        partnerEyebrow?: T;
        partnerTitle?: T;
        partnerLead?: T;
        partnerCtaLabel?: T;
        partnerCtaUrl?: T;
      };
  whatWeDo?:
    | T
    | {
        introEyebrow?: T;
        introTitle?: T;
        introLead?: T;
        introParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        introImage?: T;
        programmesEyebrow?: T;
        programmesTitle?: T;
        programmesCtaLabel?: T;
        programmesCtaUrl?: T;
        approachEyebrow?: T;
        approachTitle?: T;
        approachSteps?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        ctaTitle?: T;
        ctaBody?: T;
        ctaImage?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryUrl?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryUrl?: T;
      };
  directorMessage?:
    | T
    | {
        photo?: T;
        name?: T;
        role?: T;
        email?: T;
        linkedin?: T;
        eyebrow?: T;
        title?: T;
        greeting?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pullQuote?: T;
        signoff?: T;
        teamCtaLabel?: T;
        teamCtaUrl?: T;
      };
  projects?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        additionalParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaTitle?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  eplanPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroImage?: T;
        heroHighlights?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        heroPrimaryCtaLabel?: T;
        heroPrimaryCtaUrl?: T;
        heroSecondaryCtaLabel?: T;
        heroSecondaryCtaUrl?: T;
        visionEyebrow?: T;
        visionText?: T;
        missionEyebrow?: T;
        missionText?: T;
        executivesEyebrow?: T;
        executivesTitle?: T;
        executivesIntro?: T;
        executivesItems?:
          | T
          | {
              name?: T;
              role?: T;
              bio?: T;
              photo?: T;
              linkedin?: T;
              twitter?: T;
              facebook?: T;
              instagram?: T;
              id?: T;
            };
        sustainEyebrow?: T;
        sustainTitle?: T;
        sustainLead?: T;
        sustainNote?: T;
        sustainImage?: T;
        sustainImageAlt?: T;
        sustainPillars?:
          | T
          | {
              num?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        spotlightEyebrow?: T;
        spotlightTitle?: T;
        spotlightIntro?: T;
        spotlightItems?:
          | T
          | {
              tag?: T;
              title?: T;
              description?: T;
              href?: T;
              image?: T;
              id?: T;
            };
        spotlightSupportCtaLabel?: T;
        spotlightSupportCtaUrl?: T;
      };
  galleryPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroImage?: T;
        albumsEyebrow?: T;
        albumsTitle?: T;
        albumCtaLabel?: T;
        photosEyebrow?: T;
        photosEmptyText?: T;
        backToGalleryLabel?: T;
      };
  getInvolvedPage?:
    | T
    | {
        heroEyebrow?: T;
        fellowshipTitle?: T;
        fellowshipDescription?: T;
        primaryCtaLabel?: T;
        primaryCtaUrl?: T;
        secondaryCtaLabel?: T;
        secondaryCtaUrl?: T;
      };
  currentFellowsPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroImage?: T;
        heroStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        searchPlaceholder?: T;
        sectorFilterLabel?: T;
        defaultRoleLabel?: T;
        initialVisibleCount?: T;
        showMoreLabel?: T;
        showLessLabel?: T;
        emptyStateText?: T;
        eplanEyebrow?: T;
        eplanTitle?: T;
        eplanIntro?: T;
        eplanStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        eplanCtaLabel?: T;
        eplanCtaUrl?: T;
        involveEyebrow?: T;
        involveTitle?: T;
        involveBody?: T;
        involvePrimaryLabel?: T;
        involvePrimaryUrl?: T;
        involveSecondaryLabel?: T;
        involveSecondaryUrl?: T;
      };
  partnersPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroCtaLabel?: T;
        heroCtaUrl?: T;
        heroImage?: T;
        collabEyebrow?: T;
        collabTitle?: T;
        collabLead?: T;
        collabBenefits?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              id?: T;
            };
        collabHighlightValue?: T;
        collabHighlightTitle?: T;
        collabHighlightText?: T;
        collabImage?: T;
        ecosystemEyebrow?: T;
        ecosystemTitle?: T;
        ecosystemIntro?: T;
        ecosystemLearnMoreLabel?: T;
        ecosystemHighlightsLabel?: T;
        ecosystemCategories?:
          | T
          | {
              code?: T;
              title?: T;
              description?: T;
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
            };
        networkTitle?: T;
        networkIntro?: T;
        formEyebrow?: T;
        formTitle?: T;
        formDescription?: T;
        formSubmitLabel?: T;
      };
  donatePage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        heroImage?: T;
        heroPrimaryCtaLabel?: T;
        heroPrimaryCtaUrl?: T;
        heroSecondaryCtaLabel?: T;
        heroSecondaryCtaUrl?: T;
        whyEyebrow?: T;
        whyTitle?: T;
        whyReasons?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        waysEyebrow?: T;
        waysTitle?: T;
        waysIntro?: T;
        transferLabel?: T;
        cardStatusLabel?: T;
        cardCode?: T;
        cardTitle?: T;
        cardDescription?: T;
        cardCtaLabel?: T;
        cardCtaUrl?: T;
        momoOptions?:
          | T
          | {
              title?: T;
              subtitle?: T;
              name?: T;
              detail?: T;
              detailLabel?: T;
              badge?: T;
              logo?: T;
              id?: T;
            };
        bankTitle?: T;
        bankBranch?: T;
        bankAccountName?: T;
        bankAccountGhs?: T;
        bankAccountUsd?: T;
        bankName?: T;
        bankSwift?: T;
        bankSortCode?: T;
        bankNote?: T;
        tiersEyebrow?: T;
        tiersTitle?: T;
        tierItems?:
          | T
          | {
              label?: T;
              amountDisplay?: T;
              amountGhs?: T;
              amountUsd?: T;
              description?: T;
              isCustom?: T;
              id?: T;
            };
        questionsTitle?: T;
        questionsText?: T;
        questionsPrimaryLabel?: T;
        questionsPrimaryUrl?: T;
        questionsSecondaryLabel?: T;
        questionsSecondaryUrl?: T;
        pledgeEyebrow?: T;
        pledgeTitle?: T;
        pledgeDescription?: T;
        pledgeSubmitLabel?: T;
        pledgeSuccessTitle?: T;
        pledgeSuccessText?: T;
        pledgeChannels?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  impactPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroDescription?: T;
        heroImage?: T;
        glanceEyebrow?: T;
        glanceStats?:
          | T
          | {
              value?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
        successEyebrow?: T;
        successTitle?: T;
        communityEyebrow?: T;
        communityTitle?: T;
        communityIntro?: T;
        communityCtaLabel?: T;
        communityCtaUrl?: T;
        testimonialsEyebrow?: T;
        testimonialsTitle?: T;
        testimonialsIntro?: T;
        testimonials?:
          | T
          | {
              category?: T;
              quote?: T;
              author?: T;
              role?: T;
              org?: T;
              photo?: T;
              id?: T;
            };
        publicationsEyebrow?: T;
        publicationsTitle?: T;
        publicationsIntro?: T;
        reportsHeading?: T;
        reportsCtaLabel?: T;
        reportsCtaUrl?: T;
        researchHeading?: T;
        researchCtaLabel?: T;
        researchCtaUrl?: T;
      };
  annualReportsPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroLead?: T;
        introText?: T;
        heroImage?: T;
        reportsEyebrow?: T;
        reportsTitle?: T;
        relatedEyebrow?: T;
        relatedTitle?: T;
        ctaTitle?: T;
        ctaBody?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  team?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  tagline?: string | null;
  /**
   * Optional. Falls back to /assets/cropped-EPL-Ghana-logo.png when empty.
   */
  logo?: (string | null) | Media;
  heroSubtitle?: string | null;
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroImage?: (string | null) | Media;
  heroCtaLabel?: string | null;
  heroCtaUrl?: string | null;
  heroStatValue?: string | null;
  heroStatLabel?: string | null;
  aboutSubtitle?: string | null;
  aboutTitle?: string | null;
  aboutDescription?: string | null;
  aboutImage?: (string | null) | Media;
  aboutCtaLabel?: string | null;
  aboutCtaUrl?: string | null;
  missionBannerQuote?: string | null;
  /**
   * Optional single photo. Prefer the slideshow below for multiple images.
   */
  missionBannerImage?: (string | null) | Media;
  /**
   * Photos that crossfade behind the mission quote on the homepage. Falls back to hero slides if empty.
   */
  missionBannerImages?:
    | {
        image: string | Media;
        /**
         * Optional short label (e.g. PSF Graduation 2025)
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  fellowshipTitle?: string | null;
  fellowshipDescription?: string | null;
  fellowshipCtaLabel?: string | null;
  fellowshipCtaUrl?: string | null;
  coreValues?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Top navigation. Add a link, or leave the URL blank and add dropdown items below to turn it into a dropdown menu.
   */
  navItems?:
    | {
        label: string;
        /**
         * Where this item links to (e.g. /about). Leave blank if it only opens a dropdown.
         */
        url?: string | null;
        /**
         * Optional. Add sub-links to make this item a dropdown.
         */
        children?:
          | {
              label: string;
              url: string;
              /**
               * Optional subtitle shown under the link in the mega menu.
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary links shown in the header bar (next to the logo).
   */
  topLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    label?: string | null;
    url?: string | null;
  };
  partnerCta?: {
    enabled?: boolean | null;
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Short text under the footer logo. Leave blank to use the Site Settings tagline.
   */
  aboutText?: string | null;
  /**
   * The lists of links in the footer (e.g. Quick Links, Our Programs).
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Use {year} and it will be replaced with the current year automatically.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Add a background photo to a page’s top banner. The blue overlay stays on top, so any photo still looks on-brand. Pages without a photo here stay solid blue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-banners".
 */
export interface PageBanner {
  id: string;
  /**
   * Pick a page, then upload the photo for its top banner.
   */
  banners?:
    | {
        /**
         * The page whose banner this photo is for.
         */
        page:
          | 'About Us'
          | 'What We Do'
          | 'Message from the Country Director'
          | 'Our Team'
          | 'Projects'
          | 'Our Community'
          | 'Current Fellows'
          | 'EPLAN'
          | 'Our Partners'
          | 'Knowledge Products'
          | 'Newsletter'
          | 'Get Involved'
          | 'Contact Us'
          | 'Blog'
          | 'News & Events';
        /**
         * Wide landscape photo works best (it is cropped to fill the banner).
         */
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  heroSubtitle?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  heroCtaLabel?: T;
  heroCtaUrl?: T;
  heroStatValue?: T;
  heroStatLabel?: T;
  aboutSubtitle?: T;
  aboutTitle?: T;
  aboutDescription?: T;
  aboutImage?: T;
  aboutCtaLabel?: T;
  aboutCtaUrl?: T;
  missionBannerQuote?: T;
  missionBannerImage?: T;
  missionBannerImages?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  fellowshipTitle?: T;
  fellowshipDescription?: T;
  fellowshipCtaLabel?: T;
  fellowshipCtaUrl?: T;
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  phone?: T;
  email?: T;
  address?: T;
  facebook?: T;
  twitter?: T;
  instagram?: T;
  linkedin?: T;
  youtube?: T;
  tiktok?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  topLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        label?: T;
        url?: T;
      };
  partnerCta?:
    | T
    | {
        enabled?: T;
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  aboutText?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-banners_select".
 */
export interface PageBannersSelect<T extends boolean = true> {
  banners?:
    | T
    | {
        page?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}